version: '3.4'

services:
  db:
    restart: always
    image: mariadb:10.4.0
    container_name: db
    volumes:
      - db-data-radar:/var/lib/mysql
    ports:
      - 3306:3306
    env_file:
      - .env

  api:
    build: .
    volumes:
      - ./DataRadar:/code
    depends_on:
      - db
    entrypoint: []
    ports:
      - 8000:8000
    env_file:
      - .env

volumes:
  db-data-radar:
