# Generated by Django 3.0.5 on 2020-06-16 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("radar", "0003_monument_museum"),
    ]

    operations = [
        migrations.DeleteModel(name="Pharmacy",),
    ]
