# Generated by Django 3.0.5 on 2021-02-02 16:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radar', '0004_delete_pharmacy'),
    ]

    operations = [
        migrations.CreateModel(
            name='HighSchool',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('phone', models.CharField(max_length=9, validators=[django.core.validators.RegexValidator('^98(\\d){7}$', message='Use formato: 98XXXXXXX')])),
                ('latitude', models.DecimalField(decimal_places=7, max_digits=12)),
                ('longitude', models.DecimalField(decimal_places=7, max_digits=12)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Library',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('phone', models.CharField(max_length=9, validators=[django.core.validators.RegexValidator('^98(\\d){7}$', message='Use formato: 98XXXXXXX')])),
                ('latitude', models.DecimalField(decimal_places=7, max_digits=12)),
                ('longitude', models.DecimalField(decimal_places=7, max_digits=12)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='NurserySchool',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('phone', models.CharField(max_length=9, validators=[django.core.validators.RegexValidator('^98(\\d){7}$', message='Use formato: 98XXXXXXX')])),
                ('latitude', models.DecimalField(decimal_places=7, max_digits=12)),
                ('longitude', models.DecimalField(decimal_places=7, max_digits=12)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('phone', models.CharField(max_length=9, validators=[django.core.validators.RegexValidator('^98(\\d){7}$', message='Use formato: 98XXXXXXX')])),
                ('latitude', models.DecimalField(decimal_places=7, max_digits=12)),
                ('longitude', models.DecimalField(decimal_places=7, max_digits=12)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SecurityForce',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('phone', models.CharField(max_length=9, validators=[django.core.validators.RegexValidator('^98(\\d){7}$', message='Use formato: 98XXXXXXX')])),
                ('latitude', models.DecimalField(decimal_places=7, max_digits=12)),
                ('longitude', models.DecimalField(decimal_places=7, max_digits=12)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
